### ISSUE TITLE
Define the add new place flow

### ISSUE THREAD

**Issue by remusplesa** [remusplesa/hackathon-accessibility-app#19]
* Should we 
   * redirect to `/upload` when double clicking the map? 
   * open the drawer and add the details in there?
   * let any kind of entry be uploaded - even without accessibility features present 😄 

* Define how we add new photos / input about existing points of interest (places)

[...]

**Comment by singularity-bit** [comment]
flow:

- when user double clicks on the map it will be redirected to upload form with coordinates passed through query params
- when user clicks on an existing marker and press edit button the user will be redirected to upload page where it can edit place name, add more photos to locations & edit predictions , we are saving in browser history state of location so we can make use of existing data like photos of location 
- user can upload photos even if they are not accessible , but we are marking the location as unaccessible
