### ISSUE TITLE
Bug: Github login Error 

### ISSUE THREAD

**Issue by remusplesa** [remusplesa/hackathon-accessibility-app#36]
* tried logging in in Safari - not sure what is causing this behavior
* 
![Screenshot 2022-11-29 at 11 28 45](https://user-images.githubusercontent.com/80645758/204491514-5c84320e-9a82-4f79-80ca-1b1ee8b9636b.png)

**Comment by dbalasoiu** [comment]
I am able to login with safari, no errors 
![Screenshot 2022-11-30 at 10 31 15](https://user-images.githubusercontent.com/3178684/204746204-49968fe7-2fa5-4115-8ac1-0fc1b79a7d65.png)
